Repository lunch-12/PAPERPLE-BE, pull requests merged in 2024-09, with the labels that each got.

#10 [FEAT/#22] 페이퍼 예외 처리
  src/main/java/com/ktb/paperplebe/common/exception/DomainErrorCode.java
  src/main/java/com/ktb/paperplebe/common/exception/DomainException.java
  src/main/java/com/ktb/paperplebe/paper/exception/PaperErrorCode.java
  src/main/java/com/ktb/paperplebe/paper/exception/PaperException.java
  src/main/java/com/ktb/paperplebe/paper/exception/PaperLikeErrorCode.java
  src/main/java/com/ktb/paperplebe/paper/exception/PaperLikeException.java
  src/main/java/com/ktb/paperplebe/paper/service/PaperLikeService.java
  src/main/java/com/ktb/paperplebe/paper/service/PaperService.java
Labels: ✨feature, ✔︎pull requests

#12 [FEAT/#23] sorting 기능 추가
  build.gradle
  src/docs/asciidoc/api-documnet.adoc
  src/main/java/com/ktb/paperplebe/PaperpleBeApplication.java
  src/main/java/com/ktb/paperplebe/common/config/QuerydslConfig.java
  src/main/java/com/ktb/paperplebe/common/entity/BaseEntity.java
  src/main/java/com/ktb/paperplebe/paper/controller/PaperController.java
  src/main/java/com/ktb/paperplebe/paper/entity/Paper.java
  src/main/java/com/ktb/paperplebe/paper/repository/PaperRepository.java
  src/main/java/com/ktb/paperplebe/paper/repository/PaperRepositoryQuerydsl.java
  src/main/java/com/ktb/paperplebe/paper/repository/PaperRepositoryQuerydslImpl.java
  src/main/java/com/ktb/paperplebe/paper/service/PaperService.java
  src/main/java/com/ktb/paperplebe/search/controller/SearchController.java
  src/test/java/com/ktb/paperplebe/paper/controller/PaperControllerTest.java
  src/test/java/com/ktb/paperplebe/paper/controller/PaperLikeControllerTest.java
  src/test/java/com/ktb/paperplebe/search/controller/SearchControllerTest.java
  src/test/java/com/ktb/paperplebe/user/controller/UserControllerTest.java
Labels: 📃docs, ✨feature, ✔︎pull requests

#20 Feat/logout
  src/main/java/com/ktb/paperplebe/oauth/controller/OauthController.java
Labels: ✨feature
